version: '3.7'

services:
  dockerdeploymentapi:
    image: dockerdeploymentapi:debug
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes: 
      - ./:/app