version: '3.7'

services:
  dockerdeploymentapi:
    image: dockerdeploymentapi:prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV="production"